name: "Install dependencies"
description: "Prepare the repository and all dependencies"

runs:
  using: "composite"
  steps:
    - name: Install bun
      uses: bun/action-setup@v2

    - name: Set up node
      uses: actions/setup-node@v3
      with:
        cache: bun
        node-version: 18

    - name: Install dependencies
      shell: bash
      run: bun install